<template>
    <div>
      123
    </div>
</template>
<script>
    import {store} from 'ltsutil'
    const menuItemList =[
        {
            "apptype":1,
            "cdate":1447217704000,
            "code":"10167",
            "description":"运营商批发交易管理",
            "display":5,
            "domain":"http://work.500mi.com",
            "edate":1493375344000,
            "id":224,
            "name":"订单管理",
            "pic":"order",
            "resourcesList":[
                {
                    "apptype":1,
                    "cdate":1342499512000,
                    "code":"10048",
                    "description":"运营商批发交易管理",
                    "display":4,
                    "domain":"http://work.500mi.com",
                    "edate":1493375344000,
                    "id":86,
                    "name":"订单列表",
                    "resourcesList":[

                    ],
                    "sort":0,
                    "status":1,
                    "type":2,
                    "url":"/pages/order.html"
                },
                {
                    "apptype":1,
                    "cdate":1342499512000,
                    "code":"10048",
                    "description":"运营商批发交易管理",
                    "display":4,
                    "domain":"http://work.500mi.com",
                    "edate":1493375344000,
                    "id":87,
                    "name":"退货退款",
                    "resourcesList":[

                    ],
                    "sort":0,
                    "status":1,
                    "type":2,
                    "url":"javascript:void(0)"
                }
            ],
            "sort":1010,
            "status":1,
            "type":1
        },
        {
            "apptype":1,
            "cdate":1447217704000,
            "code":"10167",
            "description":"运营商批发交易管理",
            "display":5,
            "domain":"http://work.500mi.com",
            "edate":1493375344000,
            "id":225,
            "name":"产品管理",
            "pic":"order",
            "resourcesList":[],
            "sort":1010,
            "status":1,
            "type":1,
            "url": '/product'
        },
        {
          "apptype":1,
          "cdate":1447217704000,
          "code":"10167",
          "description":"运营商批发交易管理",
          "display":5,
          "domain":"http://work.500mi.com",
          "edate":1493375344000,
          "id":23111,
          "name":"商品管理",
          "pic":"order",
          "resourcesList":[],
          "sort":1010,
          "status":1,
          "type":1,
          "url": '/goods'
        },
        {
            "apptype":1,
            "cdate":1447217704000,
            "code":"10167",
            "description":"运营商批发交易管理",
            "display":5,
            "domain":"http://work.500mi.com",
            "edate":1493375344000,
            "id":226,
            "name":"工程商管理",
            "pic":"order",
            "resourcesList":[],
            "sort":1010,
            "status":1,
            "type":1,
            "url": '/pages/merchants.html#list'
        },
        {
            "apptype":1,
            "cdate":1447217704000,
            "code":"10167",
            "description":"运营商批发交易管理",
            "display":5,
            "domain":"http://work.500mi.com",
            "edate":1493375344000,
            "id":227,
            "name":"代客下单",
            "pic":"order",
            "resourcesList":[],
            "sort":1010,
            "status":1,
            "type":1,
            "url": '/pages/customerorder.html'
        },
        {
            "apptype":1,
            "cdate":1447217704000,
            "code":"10167",
            "description":"运营商批发交易管理",
            "display":5,
            "domain":"http://work.500mi.com",
            "edate":1493375344000,
            "id":228,
            "name":"类目管理",
            "pic":"order",
            "resourcesList":[],
            "sort":1010,
            "status":1,
            "type":1,
            "url": '/pages/category.html'
        },
        {
            "apptype":1,
            "cdate":1447217704000,
            "code":"10167",
            "description":"运营商批发交易管理",
            "display":5,
            "domain":"http://work.500mi.com",
            "edate":1493375344000,
            "id":229,
            "name":"子市场管理",
            "pic":"order",
            "resourcesList":[],
            "sort":1010,
            "status":1,
            "type":1,
            "url": '/pages/segments.html'
        },
        {
            "apptype":1,
            "cdate":1447217704000,
            "code":"10167",
            "description":"运营商批发交易管理",
            "display":5,
            "domain":"http://work.500mi.com",
            "edate":1493375344000,
            "id":230,
            "name":"库存管理",
            "pic":"order",
            "resourcesList":[],
            "sort":1010,
            "status":1,
            "type":1,
            "url": '/pages/repertory.html'
        },
    ];
    export default {
        name : "header",
        data(){
          return{

          }
        },
        methods:{

        },
        created(){

        },
    }
</script>
<style scoped>

</style>
